name: "Buildx Python Image"
on:
  release:
    types: [published]
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build Python Image
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: true
              imageName: evinedeng/python
              dockerFile: python/dockerfile
              platform: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6
              tag: latest,python3,python3.8,python3.8.5
              dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
              dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}